name: trade_stream
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^3.0.1
  flutter_native_splash: ^2.4.1
  flutter_bloc: ^8.1.6
  shimmer: ^3.0.0
  lottie: ^3.1.2
  http: ^1.2.2
  fl_chart: ^0.69.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  get_it: ^8.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_channel_ios: true
  image_path_ios: "assets/icon/icon.png"
  

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/icon.png
